### ISSUE TITLE
OSError: libmpi_cxx.so.40: cannot open shared object file: No such file or directory while import torch

### ISSUE THREAD

**Issue by adrianwojdat** [Ben-Faessler/Python3-Wheels#5]
```pi@raspberrypi:~/Shop/Python3-Wheels/pytorch $ sudo python3 -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/torch/__init__.py", line 135, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.7/dist-packages/torch/__init__.py", line 93, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmpi_cxx.so.40: cannot open shared object file: No such file or directory
```

To solve this problem we need to reinstall `openmpi`

```bash
sudo apt-get install --reinstall openmpi-bin libopenmpi-dev
```

**Comment by nikrtyd** [comment]
Quick note for Fedora/other RH-based distro users:

Sometimes this error shows up even if `openmpi` and `openmpi-devel` packages were already installed.
To fix that, you should add the path to OpenMPI libraries to LD_LIBRARY_PATH:

1. Open the config file: `sudo nano /etc/ld.so.conf.d/openmpi-x86_64.conf`.
2. Add `/usr/lib64/openmpi/lib` if it doesn't exist.
